"""Enforce case-insensitive email uniqueness via a UNIQUE index on lower(email)

Email uniqueness was enforced case-sensitively by the UNIQUE (email) constraint
from migration 0001 (Postgres auto-named it, almost certainly users_email_key).
The application layer already lowercases every email at every store/lookup site
(login/app.py: create_account, login, resolve_oauth_user, request_password_reset,
reset_password). This migration is the DB-level half: it backfills existing rows
to lowercase and replaces the case-sensitive UNIQUE (email) constraint with a
UNIQUE functional index on lower(email), so the same mailbox cannot create
duplicate accounts and existing mixed-case rows can still be matched at login.

A functional index is used rather than citext to avoid a Postgres extension / new
dependency; the app already normalizes to lowercase.

If two existing rows collapse to the same lowercased address the migration ABORTS
(RuntimeError) rather than guessing which account's wallet/transactions survive --
merging two users is a human decision. Resolve the collision manually in psql,
then re-run `flask db upgrade`.

Per the 0004 precedent, downgrade reverses only the constraint/index swap; it does
NOT un-lowercase the data (a one-way data transform).

NOTE: these migrations are hand-written, not autogenerated. Functional-index
expressions like lower(email) are compared poorly by Alembic autogenerate; do not
be alarmed by phantom drift if `flask db migrate` is ever run.

Revision ID: 0007_email_unique_ci
Revises: 0006_money_to_numeric
Create Date: 2026-06-05 00:00:00.000000

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0007_email_unique_ci"
down_revision = "0006_money_to_numeric"
branch_labels = None
depends_on = None


def upgrade():
    # 1. Pre-check: refuse to run if any two rows collapse to the same lowercased
    #    email. Merging two users' wallets/transactions is a business decision,
    #    not something to automate silently.
    bind = op.get_bind()
    collisions = bind.execute(
        sa.text(
            """
            SELECT lower(email) AS lower_email, count(*) AS n
            FROM users
            GROUP BY lower(email)
            HAVING count(*) > 1
            ORDER BY lower(email)
            """
        )
    ).fetchall()
    if collisions:
        details = ", ".join(f"{row.lower_email} (x{row.n})" for row in collisions)
        raise RuntimeError(
            "Cannot enforce case-insensitive email uniqueness: the following "
            f"lowercased emails are shared by multiple users: {details}. "
            "Manually merge or remove the duplicate accounts in psql "
            "(wallet/transaction ownership is a human decision), then re-run "
            "`flask db upgrade`."
        )

    # 2. Backfill: normalize all existing emails to lowercase. Safe under the
    #    still-present case-sensitive UNIQUE (email) -- step 1 proved the final
    #    values are collision-free.
    op.execute("UPDATE users SET email = lower(email) WHERE email <> lower(email);")

    # 3. Drop the old case-sensitive UNIQUE (email) constraint. Its auto-name is
    #    almost certainly users_email_key, but discover it from the catalog by
    #    DEFINITION so a differently-named constraint is still dropped (a bare
    #    DROP CONSTRAINT IF EXISTS users_email_key would silently no-op and leave
    #    the case-sensitive constraint in place, defeating this migration).
    op.execute(
        """
        DO $$
        DECLARE
            cname text;
        BEGIN
            SELECT con.conname INTO cname
            FROM   pg_constraint con
            JOIN   pg_class      rel ON rel.oid = con.conrelid
            JOIN   pg_namespace  nsp ON nsp.oid = rel.relnamespace
            WHERE  rel.relname = 'users'
              AND  nsp.nspname = current_schema()
              AND  con.contype = 'u'
              AND  pg_get_constraintdef(con.oid) = 'UNIQUE (email)';

            IF cname IS NOT NULL THEN
                EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', cname);
            END IF;
        END $$;
        """
    )

    # 4. Create the case-insensitive UNIQUE functional index. Non-concurrent on
    #    purpose: CREATE INDEX CONCURRENTLY cannot run inside a transaction block,
    #    and Flask-Migrate wraps each migration in one. The users table is tiny,
    #    so the brief lock is a non-issue.
    op.execute("CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));")


def downgrade():
    # Reverse only the constraint/index swap; do NOT un-lowercase the data
    # (one-way transform, per the 0004 precedent). Recreating the case-sensitive
    # constraint is safe because all emails are now lowercase. Restore the exact
    # original name so a re-upgrade's catalog lookup finds and drops it cleanly.
    op.execute("DROP INDEX IF EXISTS uq_users_email_lower;")
    op.create_unique_constraint("users_email_key", "users", ["email"])
